apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc-exporter
  namespace: developerautomation-xavgy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccc-exporter
  template:
    metadata:
      labels:
        app: ccc-exporter
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      #serviceAccountName: <TODO>
      containers:
        - name: app
          image: 642375522597.dkr.ecr.eu-west-1.amazonaws.com/ccc-exporter:sha-$(image_tag)
          ports:
            - name: metrics
              containerPort: 8888
          resources:
            requests:
              memory: "20Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          env:
            - name: CCC_PROMETHEUS_ENDPOINT
              value: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local"
            - name: CCC_WORKER_INTERVALSECONDS
              value: "5"
            - name: CCC_S3_BUCKETNAME
              value: "$(S3_BUCKET_NAME)"
            - name: CCC_S3_BUCKETKEY
              value: "prod"
          envFrom:
            - secretRef:
                name: ccc-exporter-confluent-cloud-api-access
          volumeMounts:
            - name: ccc-exporter-config
              mountPath: /app/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: ccc-exporter-config
          configMap:
            name: ccc-exporter
            items:
              - key: config.json
                path: config.json
