apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc-exporter
  namespace: developerautomation-xavgy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccc-exporter
  template:
    metadata:
      labels:
        app: ccc-exporter
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      #serviceAccountName: <TODO>
      containers:
        - name: app
          image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice/ccc-exporter:$(image-tag)
          ports:
            - name: metrics
              containerPort: 8888
          resources:
            requests:
              memory: "20Mi"
              cpu: "50m"
            limits:
              memory: "100Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                name: ccc-exporter-confluent-cloud-api-access