apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccc-exporter
  namespace: developerautomation-xavgy
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${S3_AWS_ACCOUNT_ID}:role/ccc-exporter-s3-access
    eks.amazonaws.com/sts-regional-endpoints: "true"