name: 'Build & push container'
description: 'Build container image and afterwards push it to AWS ECR'
inputs: #we give all this stuff in the 'with' block of the step in the workflow that uses this action
  dockerfile_path:
    required: true
    description: 'Path where Dockerfile resides'
  context_path:
    required: true
    description: 'Path to be used for build context'
  tag:
    required: true
    description: 'Image tag'
  repo:
    required: true
    description: 'Repo in ECR'
  role_arn:
    required: true
    description: 'IAM role for pushing to ECR'
  aws_region:
    required: true
    description: 'AWS region used when assuming the IAM role'
outputs:
  sha:
    description: "SHA that is used for a tag"
    value: ${{ steps.vars.outputs.sha_short }}
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role_arn }}
        role-session-name: gh-ecr-push
        aws-region: ${{ inputs.aws_region }}
    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.context_path }}
        push: true
        tags: |
          ${{ inputs.repo }}:${{ inputs.tag }}